site_name: Docs Seg ERP


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  # - pymdownx.tabbed
  # - attr_list
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css 


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


nav:
  - Visão geral: visao_geral/visao_geral.md
  - Dicionário Ubíquo: dicionario/dicionario.md   
  - Modulos:  
    - Estoque: modulos/estoque.md
  - Banco de dados:  0.0.1/database/tabelas.md


theme:
  name: material
  # custom_dir: mkdocs-material/material
  # custom_dir: mkdocs-material-7.3.6/material
  custom_dir: mkdocs-material-8.2.9/material

  palette:
    primary: blue

  features:
    - content.code.annotate
  # features:
  #   - navigation.expand

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo


  # features:
  #   - navigation.expand

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo